# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "windows-2019"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      yarn install
      yarn build
    displayName: "Install"

  - script: |
      yarn build
    displayName: "Build"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)"
      Contents: |
        node_modules/**/*
        dist/**/*
        public/**/*
        web.config
      TargetFolder: "$(System.DefaultWorkingDirectory)/deploy"
      CleanTargetFolder: true
      OverWrite: true

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/deploy"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true
  
  - task: AzureAppServiceSettings@1
    inputs:
      azureSubscription: 'DEV-IO(a4e96bcd-59dc-4d66-b2f7-5547ad157c12)'
      appName: 'io-lab-app-testas'
      resourceGroupName: 'io-lab-rg-mobileapp'
      appSettings: |
        [
          {
            "name": "APP_SECRET",
            "value": "@Microsoft.KeyVault(SecretUri=https://io-lab-kv-common.vault.azure.net/secrets/testas-APP-SECRET/)",
            "slotSetting": false
          }
        ]

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: "AzureRM"
      azureSubscription: "DEV-IO(a4e96bcd-59dc-4d66-b2f7-5547ad157c12)"
      appType: "webApp"
      WebAppName: "io-lab-app-testas"
      packageForLinux: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
